services:
  - type: web
    name: vayudrishti-api
    runtime: python
    region: oregon
    plan: free
    buildCommand: pip install -r backend/requirements.txt
    startCommand: uvicorn backend.main:app --host 0.0.0.0 --port $PORT
    healthCheckPath: /
    autoDeploy: true
    envVars:
      - key: PYTHON_VERSION
        value: 3.11.9
      - key: ENVIRONMENT
        value: production
      - key: DATABASE_NAME
        value: vayudrishti
      - key: CORS_ORIGINS
        value: "*"
      - key: MONGODB_URI
        sync: false
      - key: GROQ_API_KEY
        sync: false
      - key: AQICN_API_KEY
        sync: false
      - key: OPENWEATHERMAP_API_KEY
        sync: false
      - key: TOMTOM_API_KEY
        sync: false
      - key: DATA_GOV_IN_API_KEY
        value: 579b464db66ec23bdd000001cdd3946e44ce4aad7209ff7b23ac571b
