"""
Graphify Codebase Dependency & Knowledge Graph Builder
Traverses backend and frontend directories to build an architectural graph.
"""

import os
import re
from pathlib import Path

def scan_project(root_dir: str):
    root = Path(root_dir)
    backend_dir = root / "backend"
    frontend_dir = root / "frontend" / "src"

    routers = []
    services = []
    pages = []
    components = []
    api_methods = []

    # Scan Backend Routers
    router_dir = backend_dir / "routers"
    if router_dir.exists():
        for f in router_dir.glob("*.py"):
            if f.name != "__init__.py":
                with open(f, "r", encoding="utf-8", errors="ignore") as file:
                    content = file.read()
                    endpoints = re.findall(r'@router\.(get|post|put|patch|delete)\(["\']([^"\']+)["\']', content)
                    routers.append({
                        "file": f"backend/routers/{f.name}",
                        "name": f.stem,
                        "endpoints": [f"{method.upper()} {path}" for method, path in endpoints]
                    })

    # Scan Backend Services
    service_dir = backend_dir / "services"
    if service_dir.exists():
        for f in service_dir.glob("*.py"):
            if f.name != "__init__.py":
                with open(f, "r", encoding="utf-8", errors="ignore") as file:
                    content = file.read()
                    classes = re.findall(r'class\s+([A-Za-z0-9_]+)', content)
                    funcs = re.findall(r'async\s+def\s+([A-Za-z0-9_]+)|def\s+([A-Za-z0-9_]+)', content)
                    func_names = [f[0] or f[1] for f in funcs if not (f[0] or f[1]).startswith("_")]
                    services.append({
                        "file": f"backend/services/{f.name}",
                        "name": f.stem,
                        "classes": classes,
                        "functions": func_names[:8]
                    })

    # Scan Frontend Pages
    pages_dir = frontend_dir / "pages"
    if pages_dir.exists():
        for f in pages_dir.glob("*.jsx"):
            pages.append({
                "file": f"frontend/src/pages/{f.name}",
                "name": f.stem
            })

    # Scan Frontend Components
    comp_dir = frontend_dir / "components"
    if comp_dir.exists():
        for sub in comp_dir.iterdir():
            if sub.is_dir():
                sub_comps = [f.stem for f in sub.glob("*.jsx")]
                components.append({
                    "category": sub.name,
                    "items": sub_comps
                })

    # Scan Frontend API Client
    api_file = frontend_dir / "services" / "api.js"
    if api_file.exists():
        with open(api_file, "r", encoding="utf-8", errors="ignore") as f:
            content = f.read()
            api_exports = re.findall(r'export\s+const\s+([a-zA-Z0-9_]+)\s*=\s*{([^}]+)}', content, re.DOTALL)
            for name, body in api_exports:
                methods = [m.strip() for m in re.findall(r'([a-zA-Z0-9_]+)\s*:', body)]
                api_methods.append({
                    "service": name,
                    "methods": methods
                })

    return {
        "routers": routers,
        "services": services,
        "pages": pages,
        "components": components,
        "api_methods": api_methods
    }

def generate_markdown_graph(data: dict) -> str:
    md = [
        "# CODEBASE_GRAPH.md — Full System Relationship & Knowledge Graph",
        "",
        "> Generated by Graphify for VayuDrishti (वायुदृष्टि).",
        "> Automatically maps the call paths, module relationships, and API-to-database contracts.",
        "",
        "---",
        "",
        "## 1. High-Level System Architecture",
        "",
        "```mermaid",
        "graph TD",
        '    subgraph Frontend["Frontend (React / Vite)"]',
        '        P_Dash["Dashboard / WarRoom / Advisory Pages"]',
        '        API_Client["api.js Client"]',
        '        Components["Bento Panels, MapLibre & ECharts"]',
        "    end",
        "",
        '    subgraph Backend["FastAPI Backend (Port 8000)"]',
        '        Main["main.py (Lifespan & Middleware)"]',
        '        Routers["Routers (AQI, Predict, Advisory, GRAP, Replay)"]',
        '        Services["Services (Ingestion, ML Prediction, RAG, Agents)"]',
        '        ML["ML Pipeline (XGBoost Forecaster)"]',
        "    end",
        "",
        '    subgraph Storage["Data & Cache Tier"]',
        '        MongoDB[("MongoDB (vayu_drishti)")]',
        '        LLMCache[("LLM Response Cache")]',
        '        ReplayDB[("Crisis Episode Replays")]',
        "    end",
        "",
        "    P_Dash --> API_Client",
        "    API_Client -->|REST API v1| Routers",
        "    Routers --> Services",
        "    Services --> ML",
        "    Services --> MongoDB",
        "    Services --> LLMCache",
        "    Services --> ReplayDB",
        "```",
        "",
        "---",
        "",
        "## 2. API Endpoints & Route Map",
        "",
        "| Router | File | Exposed Endpoints |",
        "|---|---|---|"
    ]

    for r in data["routers"]:
        endpoints_str = "<br>".join([f"`{e}`" for e in r["endpoints"]]) if r["endpoints"] else "`None`"
        md.append(f"| **{r['name'].title()}** | `{r['file']}` | {endpoints_str} |")

    md.extend([
        "",
        "---",
        "",
        "## 3. Backend Services & Core Responsibilities",
        "",
        "| Service | Key Classes / Functions | Primary Responsibility |",
        "|---|---|---|"
    ])

    for s in data["services"]:
        items = ", ".join([f"`{fn}`" for fn in s["functions"]]) if s["functions"] else "Core logic"
        md.append(f"| **{s['name']}** | {items} | Handles {s['name'].replace('_', ' ')} logic & database queries |")

    md.extend([
        "",
        "---",
        "",
        "## 4. Frontend Component & Page Hierarchy",
        "",
        "### Pages (`frontend/src/pages/`)",
        ""
    ])

    for p in data["pages"]:
        md.append(f"- **`{p['name']}`** (`{p['file']}`)")

    md.extend([
        "",
        "### Component Categories (`frontend/src/components/`)",
        ""
    ])

    for c in data["components"]:
        items_str = ", ".join([f"`{i}`" for i in c["items"]]) if c["items"] else "None"
        md.append(f"- **{c['category'].title()}**: {items_str}")

    md.extend([
        "",
        "---",
        "",
        "## 5. API Client Call Graph (`frontend/src/services/api.js`)",
        "",
        "| API Service Export | Methods Available | Backend Target |",
        "|---|---|---|"
    ])

    for a in data["api_methods"]:
        methods_str = ", ".join([f"`{m}`" for m in a["methods"]])
        md.append(f"| **`{a['service']}`** | {methods_str} | `/api/v1/{a['service'].replace('Api', '')}` |")

    md.extend([
        "",
        "---",
        "",
        "## 6. Degradation & Fallback Call Chains (Non-Negotiable)",
        "",
        "```mermaid",
        "flowchart TD",
        '    subgraph AdvisoryLadder["Advisory Degradation Ladder"]',
        "        A1[Multi-Agent LangGraph System] -->|Quota/Fail| A2[Raw Gemini LLM Call]",
        "        A2 -->|Timeout/429| A3[Deterministic Rule & Template Engine]",
        "    end",
        "",
        '    subgraph IngestionLadder["Ingestion Degradation Ladder"]',
        "        I1[AQICN Live Real-Time API] -->|Fail/Missing| I2[OpenWeatherMap Air Quality API]",
        "        I2 -->|Fail/No Key| I3[Physically-Grounded Mathematical Simulator]",
        "    end",
        "",
        '    subgraph ForecastLadder["Forecasting Degradation Ladder"]',
        "        F1[Trained XGBoost Regressor] -->|Missing Features/Weights| F2[Lag-Statistical Weighted Rolling Forecaster]",
        "    end",
        "```",
        ""
    ])

    return "\n".join(md)

if __name__ == "__main__":
    project_root = Path(__file__).resolve().parent.parent.parent.parent.parent
    data = scan_project(str(project_root))
    markdown_output = generate_markdown_graph(data)
    
    out_file = project_root / "CODEBASE_GRAPH.md"
    with open(out_file, "w", encoding="utf-8") as f:
        f.write(markdown_output)
    print(f"[SUCCESS] Codebase graph generated at: {out_file}")
