"""
Understand-Anything Architecture Visualizer Script
Generates detailed Mermaid architectural diagrams for the project.
"""

from pathlib import Path

def generate_architecture_map(root_dir: str):
    root = Path(root_dir)
    
    content = """# ARCHITECTURE_MAP.md — Visual System Architecture & Flow

> Generated by Understand-Anything for VayuDrishti (वायुदृष्टि).

---

## 1. End-to-End System Flow & Data Pipeline

```mermaid
graph TB
    subgraph DataIngestion["1. Telemetry Ingestion Layer"]
        AQICN["AQICN Open Data API"]
        OWM["OpenWeatherMap API"]
        OpenMeteo["Open-Meteo Weather API"]
        Sim["Physics-Based Weather & Emission Simulator"]
        Scheduler["Background Async Scheduler (60s loop)"]
    end

    subgraph BackendCore["2. FastAPI Core Services"]
        IngestSvc["Data Ingestion Service"]
        MLPredictSvc["ML XGBoost Prediction Service"]
        AttributionSvc["Source Attribution & Trajectory Service"]
        GRAPSvc["GRAP Stage Policy Engine"]
        EnforceSvc["Enforcement Anomaly Scanner"]
        AdvisorySvc["LangGraph Multi-Agent Advisory Agent"]
    end

    subgraph DataStorage["3. Persistence & Caching Tier"]
        MongoStations[("MongoDB: Stations & Historical Readings")]
        MongoActions[("MongoDB: Enforcement Actions")]
        LLMCache[("MongoDB: Cached LLM Responses (1h TTL)")]
        ReplayEpisodes[("Crisis Episode Replay Store")]
    end

    subgraph ClientUI["4. Frontend React Dashboard"]
        DashView["Real-Time City Dashboard"]
        WarRoomView["GRAP Emergency War Room"]
        PredictView["72h XGBoost + SHAP Predictions"]
        AdvisoryView["Citizen & Vulnerability Advisories"]
        ReplaySwitcher["Historical Crisis Episode Replay"]
    end

    AQICN --> IngestSvc
    OWM --> IngestSvc
    OpenMeteo --> IngestSvc
    Sim --> IngestSvc
    Scheduler --> IngestSvc

    IngestSvc --> MongoStations
    MongoStations --> MLPredictSvc
    MongoStations --> AttributionSvc
    MongoStations --> GRAPSvc
    MongoStations --> EnforceSvc
    MongoStations --> AdvisorySvc

    AdvisorySvc <--> LLMCache
    EnforceSvc --> MongoActions
    ReplayEpisodes --> IngestSvc

    MongoStations --> DashView
    MLPredictSvc --> PredictView
    GRAPSvc --> WarRoomView
    AdvisorySvc --> AdvisoryView
    ReplayEpisodes --> ReplaySwitcher
```

---

## 2. API Request-Response Sequence

```mermaid
sequenceDiagram
    autonumber
    actor User as City Administrator / Citizen
    participant UI as React Frontend
    participant API as FastAPI Router
    participant Service as Domain Service Layer
    participant Cache as LLM Cache / Memory
    participant DB as MongoDB

    User->>UI: View Live Air Quality & Forecast
    UI->>API: GET /api/v1/predict/forecast?station_id=delhi_01
    API->>Service: get_forecast_for_station(delhi_01)
    Service->>DB: Query 48h historical lag features
    DB-->>Service: Return hourly PM2.5 / PM10 / Wind series
    Service->>Service: Run XGBoost ML Model inference
    Service-->>API: 72h Hourly Predictions + Confidence Bounds
    API-->>UI: 200 OK (JSON Forecast Payload)
    UI-->>User: Render ECharts Timeline with Confidence Bands
```

---

## 3. Degradation & Graceful Fallback Architecture

```mermaid
stateDiagram-v2
    [*] --> PrimaryService: Ingest Real-Time Telemetry
    PrimaryService --> SecondaryService: API 429 / Network Failure
    SecondaryService --> SimulatorFallback: Secondary API Unavailable
    SimulatorFallback --> ActiveState: Serve Deterministic Telemetry
    ActiveState --> [*]
```
"""

    out_file = root / "ARCHITECTURE_MAP.md"
    with open(out_file, "w", encoding="utf-8") as f:
        f.write(content)
    print(f"[SUCCESS] Architecture map generated at: {out_file}")

if __name__ == "__main__":
    project_root = Path(__file__).resolve().parent.parent.parent.parent.parent
    generate_architecture_map(str(project_root))
